/**
 * @file RenderCommand.h
 * @brief Declaration of the render command interface.
 * @details This file defines the RenderCommand abstraction used to encapsulate
 * GPU draw or state-change instructions. These commands are generated by the renderer
 * and submitted to the graphics API backend (e.g., OpenGL, Vulkan) to perform actual
 * rendering operations such as drawing meshes, clearing buffers, or setting pipeline state.
 * @author
 * @date
 * Copyright (C) 2025 DigiPen Institute of Technology.
 * Reproduction or disclosure of this file or its contents without the
 * prior written consent of DigiPen Institute of Technology is prohibited.
 */

#pragma once
#ifndef __RENDER_COMMAND_H__
#define __RENDER_COMMAND_H__

#include <cstdint>
#include <glm-0.9.9.8/glm/glm.hpp>

namespace gam300 {

	struct RenderCommand 
	{
		uint32_t  vao;
		uint32_t  shader;
		uint32_t  indexCount;
		glm::mat4 transform;
	};
}

#endif // !__RENDER_COMMAND_H__
